In [9]:
import APC as APyC
import plotly.graph_objects as go
import numpy as np

In [10]:
def spheres(size,pos=[0,0,0],res=100):
    #angular coordinates
    theta = np.linspace(0,2*np.pi,res)
    phi = np.linspace(0,np.pi,res)
    #cartesian coordinates
    x0 = pos[0]+size*np.outer(np.cos(theta),np.sin(phi))
    y0 = pos[1]+size*np.outer(np.sin(theta),np.sin(phi))
    z0 = pos[2]+size*np.outer(np.ones(res),np.cos(phi))

    return x0,y0,z0

def plot_sphere(size,color='blue',opacity=0.3,pos=[0,0,0],res=100):
    x,y,z = spheres(size,pos,res)
    trace = go.Surface(x=x,y=y,z=z,colorscale=[[0,color],[1,color]],opacity=opacity,showscale=False)
    return trace

In [13]:
#LEO
r0 = [6500, 0.0, 0.0];                                    # Initial Position (km)
v0 = (2, 7.90882662, 0.0);                              # Initial Velocity (km/s)
t0 = 0.0;                                                 # Initial Times (s)
tf = 1.2*5059.648765;                                     # Final Time (s)
# #MEO
# r0 = [9000.0, 0.0, 0.0];                                    # Initial Position (km)
# v0 = [0.0, 6.7419845635570, 1.806509319188210];             # Initial Velocity (km/s)
# t0 = 0.0;                                                   # Initial Times (s)
# tf = 10*9.952014050491189e+03;                              # Final Time (s)

#run APC code and save to textfile
APyC.Propagate(r0,v0,t0,tf)

#read data from textfile
output = np.loadtxt('output.txt')
ts = output[:,0]
Xs = output[:,1:4]
Vs = output[:,4:7]
H = output[:,7]


"""Plot topdown view"""
trace2d = go.Scatter(x=Xs[:,0],y=Xs[:,1],mode = 'lines')
fig2d = go.Figure(data=[trace2d])
fig2d.update_layout(
    #scene_aspectmode='data',
    showlegend=False,
    width = 800,
    height = 800,
    margin=dict(l=20, r=20, t=20, b=20))
fig2d.show()


# trace = go.Scatter3d(x=Xs[:,0],y=Xs[:,1],z=Xs[:,2],mode='lines',line=dict(color='red'))
# trace2 = plot_sphere(6378,res=30)
# fig = go.Figure(data=[trace, trace2])
# fig.update_coloraxes(showscale=False)
# fig.update_layout(
#     scene_aspectmode='data',
#     showlegend=False,
#     width = 800,
#     height = 800,
#     margin=dict(l=20, r=20, t=20, b=20)
# )
# fig.show()

ValueError: vector

In [4]:
#read data from test output
output = np.loadtxt('output_test.txt')
ts = output[:,0]
Xs = output[:,1:4]
Vs = output[:,4:7]
H = output[:,7]


"""Plot topdown view"""
trace2d = go.Scatter(x=Xs[:,0],y=Xs[:,1],mode = 'lines')
fig2d = go.Figure(data=[trace2d])
fig2d.update_layout(
    #scene_aspectmode='data',
    showlegend=False,
    width = 800,
    height = 800,
    margin=dict(l=20, r=20, t=20, b=20))
fig2d.show()


# trace = go.Scatter3d(x=Xs[:,0],y=Xs[:,1],z=Xs[:,2],mode='lines',line=dict(color='red'))
# trace2 = plot_sphere(6378,res=30)
# fig = go.Figure(data=[trace, trace2])
# fig.update_coloraxes(showscale=False)
# fig.update_layout(
#     scene_aspectmode='data',
#     showlegend=False,
#     width = 800,
#     height = 800,
#     margin=dict(l=20, r=20, t=20, b=20)
# )
# fig.show()

In [5]:
print(Vs)

[[ 1.00000000e+00  7.90882662e+00 -8.19180694e-24]
 [ 7.17892621e-01  7.90370024e+00 -1.19197804e-07]
 [ 4.38747021e-01  7.88851707e+00  3.11236319e-07]
 [ 1.62882313e-01  7.86357345e+00  1.43651344e-06]
 [-1.09405088e-01  7.82916995e+00  3.05159216e-06]
 [-3.77841209e-01  7.78561062e+00  4.86254784e-06]
 [-6.42173941e-01  7.73320087e+00  6.48639362e-06]
 [-9.02171409e-01  7.67224622e+00  7.68692210e-06]
 [-1.15762109e+00  7.60305183e+00  8.55853400e-06]
 [-1.40832957e+00  7.52592158e+00  9.27936329e-06]
 [-1.65412178e+00  7.44115668e+00  9.91251372e-06]
 [-1.89483975e+00  7.34905457e+00  1.04860583e-05]
 [-2.13034131e+00  7.24990824e+00  1.10453031e-05]
 [-2.36049900e+00  7.14400584e+00  1.15953834e-05]
 [-2.58519916e+00  7.03163025e+00  1.20892228e-05]
 [-2.80434097e+00  6.91305876e+00  1.24882805e-05]
 [-3.01783552e+00  6.78856292e+00  1.28101583e-05]
 [-3.22560518e+00  6.65840838e+00  1.31122108e-05]
 [-3.42758306e+00  6.52285457e+00  1.34400461e-05]
 [-3.62371213e+00  6.38215434e+