In [1]:
import APC as APyC
import plotly.graph_objects as go
import numpy as np

In [1]:
def spheres(size,pos=[0,0,0],res=100):
    #angular coordinates
    theta = np.linspace(0,2*np.pi,res)
    phi = np.linspace(0,np.pi,res)
    #cartesian coordinates
    x0 = pos[0]+size*np.outer(np.cos(theta),np.sin(phi))
    y0 = pos[1]+size*np.outer(np.sin(theta),np.sin(phi))
    z0 = pos[2]+size*np.outer(np.ones(res),np.cos(phi))

    return x0,y0,z0

def plot_sphere(size,color='blue',opacity=0.3,pos=[0,0,0],res=100):
    x,y,z = spheres(size,pos,res)
    trace = go.Surface(x=x,y=y,z=z,colorscale=[[0,color],[1,color]],opacity=opacity,showscale=False)
    return trace

In [2]:
#LEO
r0 = [6500, 0.0, 0.0];                                    # Initial Position (km)
v0 = [0.0, 7.90882662, 0.0];                              # Initial Velocity (km/s)
t0 = 0.0;                                                 # Initial Times (s)
tf = 1.*5059.648765;                                     # Final Time (s)
# #MEO
# r0 = [9000.0, 0.0, 0.0];                                    # Initial Position (km)
# v0 = [0.0, 6.7419845635570, 1.806509319188210];             # Initial Velocity (km/s)
# t0 = 0.0;                                                   # Initial Times (s)
# tf = 10*9.952014050491189e+03;                              # Final Time (s)

#run APC code and save to textfile
states = APyC.Propagate(r0,v0,t0,tf)

#read data from textfile
output = np.loadtxt('output.txt')
ts = output[:,0]
Xs = output[:,1:4]
Vs = output[:,4:7]
H = output[:,7]


"""Plot topdown view"""
trace2d = go.Scatter(x=Xs[:,0],y=Xs[:,1],mode = 'lines')
fig2d = go.Figure(data=[trace2d])
fig2d.update_layout(
    #scene_aspectmode='data',
    showlegend=False,
    width = 800,
    height = 800,
    margin=dict(l=20, r=20, t=20, b=20))
fig2d.show()


# trace = go.Scatter3d(x=Xs[:,0],y=Xs[:,1],z=Xs[:,2],mode='lines',line=dict(color='red'))
# trace2 = plot_sphere(6378,res=30)
# fig = go.Figure(data=[trace, trace2])
# fig.update_coloraxes(showscale=False)
# fig.update_layout(
#     scene_aspectmode='data',
#     showlegend=False,
#     width = 800,
#     height = 800,
#     margin=dict(l=20, r=20, t=20, b=20)
# )
# fig.show()

NameError: name 'APyC' is not defined

In [4]:
from sys import platform

In [5]:
print(Vs)

[[-0.7124219   6.70783188  1.78798073]
 [-0.85900957  6.69112268  1.7818903 ]
 [-1.00508818  6.67113288  1.77492578]
 ...
 [-1.081623    6.66600785  1.75632269]
 [-1.22695676  6.64194866  1.74669728]
 [-1.37158626  6.61464158  1.73621867]]
