In [11]:
import APC as APyC
import plotly.graph_objects as go
import numpy as np

In [12]:
def spheres(size,pos=[0,0,0],res=100):
    #angular coordinates
    theta = np.linspace(0,2*np.pi,res)
    phi = np.linspace(0,np.pi,res)
    #cartesian coordinates
    x0 = pos[0]+size*np.outer(np.cos(theta),np.sin(phi))
    y0 = pos[1]+size*np.outer(np.sin(theta),np.sin(phi))
    z0 = pos[2]+size*np.outer(np.ones(res),np.cos(phi))

    return x0,y0,z0

def plot_sphere(size,color='blue',opacity=0.3,pos=[0,0,0],res=100):
    x,y,z = spheres(size,pos,res)
    trace = go.Surface(x=x,y=y,z=z,colorscale=[[0,color],[1,color]],opacity=opacity,showscale=False)
    return trace

In [16]:
#LEO
# r0 = [6500, 0.0, 0.0];                                    # Initial Position (km)
# v0 = [0.0, 7.90882662, 0.0];                              # Initial Velocity (km/s)
# t0 = 0.0;                                                 # Initial Times (s)
# tf = 1.2*5059.648765;                                     # Final Time (s)
#MEO
r0 = [9000.0, 0.0, 0.0];                                    # Initial Position (km)
v0 = [0.0, 6.7419845635570, 1.806509319188210];             # Initial Velocity (km/s)
t0 = 0.0;                                                   # Initial Times (s)
tf = 10*9.952014050491189e+03;                              # Final Time (s)

#run APC code and save to textfile
APyC.Propagate(r0,v0,t0,tf)

#read data from textfile
output = np.loadtxt('output.txt')
ts = output[:,0]
Xs = output[:,1:4]
Vs = output[:,4:7]
H = output[:,7]


trace = go.Scatter3d(x=Xs[:,0],y=Xs[:,1],z=Xs[:,2],mode='lines',line=dict(color='red'))
trace2 = plot_sphere(6378,res=30)
fig = go.Figure(data=[trace, trace2])
fig.update_coloraxes(showscale=False)
fig.update_layout(
    scene_aspectmode='data',
    showlegend=False,
    width = 800,
    height = 800,
    margin=dict(l=20, r=20, t=20, b=20)
)
fig.show()

NSt3__16vectorIdNS_9allocatorIdEEEEfinished loading matricesfinished loading matricesElapsed time: 0.206024 s	Func Evals: 7066	Hmax 6.1673614923345076E-14


In [14]:
from sys import platform

In [15]:
print(Vs)

[[-5.90183936e+00  5.19184870e+00  9.05056586e-05]
 [-6.07988414e+00  4.97600790e+00  8.73392490e-05]
 [-6.24986845e+00  4.75412166e+00  8.36585090e-05]
 [-6.41159122e+00  4.52650321e+00  7.96561717e-05]
 [-6.56486492e+00  4.29347156e+00  7.56380850e-05]
 [-6.70951510e+00  4.05535152e+00  7.16535474e-05]
 [-6.84538091e+00  3.81247311e+00  6.75443057e-05]
 [-6.97231497e+00  3.56517047e+00  6.33617137e-05]
 [-7.09018357e+00  3.31378115e+00  5.90239992e-05]
 [-7.19886568e+00  3.05864540e+00  5.41860360e-05]
 [-7.29825294e+00  2.80010743e+00  4.87945192e-05]
 [-7.38825183e+00  2.53851413e+00  4.31493409e-05]
 [-7.46878256e+00  2.27421229e+00  3.75674050e-05]
 [-7.53977713e+00  2.00754966e+00  3.22042613e-05]
 [-7.60118095e+00  1.73887563e+00  2.70122683e-05]
 [-7.65295328e+00  1.46853919e+00  2.19410431e-05]
 [-7.69506619e+00  1.19688822e+00  1.69217707e-05]
 [-7.72750414e+00  9.24269375e-01  1.18122752e-05]
 [-7.75026370e+00  6.51027922e-01  6.84517204e-06]
 [-7.76335373e+00  3.77507435e-