In [16]:
import APC as APyC
import plotly.graph_objects as go
import numpy as np

In [17]:
def spheres(size,pos=[0,0,0],res=100):
    #angular coordinates
    theta = np.linspace(0,2*np.pi,res)
    phi = np.linspace(0,np.pi,res)
    #cartesian coordinates
    x0 = pos[0]+size*np.outer(np.cos(theta),np.sin(phi))
    y0 = pos[1]+size*np.outer(np.sin(theta),np.sin(phi))
    z0 = pos[2]+size*np.outer(np.ones(res),np.cos(phi))

    return x0,y0,z0

def plot_sphere(size,color='blue',opacity=0.3,pos=[0,0,0],res=100):
    x,y,z = spheres(size,pos,res)
    trace = go.Surface(x=x,y=y,z=z,colorscale=[[0,color],[1,color]],opacity=opacity,showscale=False)
    return trace

In [18]:
# # LEO
# r0 = [7000, 1, 0.0];                                    # Initial Position (km)
# v0 = [0.0, 8.003798178945150, 0.0];                              # Initial Velocity (km/s)
# t0 = 0.0;                                                 # Initial Times (s)
# tf = 12*5059.648765;                                     # Final Time (s)
# #MEO
# r0 = [9000.0, 0.0, 0.0];                                    # Initial Position (km)
# v0 = [0.0, 6.7419845635570, 1.806509319188210];             # Initial Velocity (km/s)
# t0 = 0.0;                                                   # Initial Times (s)
# tf = 10*9.952014050491189e+03;                              # Final Time (s)
#Molniya
r0 = [7435.12, 0.0, 0.0];                            # Initial Position (km)
v0 = [0.0, 4.299654205302486, 8.586211043023614];    # Initial Velocity (km/s)
t0    = 0.0;                                            # Initial Times (s)
tf    = 1.2*4.306316113361824e+04;                      # Final Time (s)

#run APC code and save to textfile
APyC.Propagate(r0,v0,t0,tf)

#read data from textfile
output = np.loadtxt('output.txt')
ts = output[:,0]
Xs = output[:,1:4]
Vs = output[:,4:7]
H = output[:,7]


trace = go.Scatter3d(x=Xs[:,0],y=Xs[:,1],z=Xs[:,2],mode='lines',line=dict(color='red'))
trace2 = plot_sphere(6378,res=30)
fig = go.Figure(data=[trace, trace2])
fig.update_coloraxes(showscale=False)
fig.update_layout(
    scene_aspectmode='data',
    showlegend=False,
    width = 800,
    height = 800,
    margin=dict(l=20, r=20, t=20, b=20)
)
fig.show()

NSt3__16vectorIdNS_9allocatorIdEEEEfinished loading matricesfinished loading matricesElapsed time: 0.051614 s	Func Evals: 1429	Hmax 1.4955914579757375E-14


In [19]:
1.2*5059.648765

6071.578517999999

In [20]:
print(Vs)

[[-2.83199527 -0.35214123 -0.71249631]
 [-2.82289664 -0.35454946 -0.7172733 ]
 [-2.81382081 -0.35694136 -0.72201774]
 ...
 [-0.76565723 -0.67656694 -1.35492148]
 [-0.75966527 -0.676953   -1.35565825]
 [-0.75367681 -0.67733588 -1.35638868]]
